name: "Setup Environment"
description: "Setting environment for the project"

inputs:
  task-version:
    description: "Task version"
    required: true
    default: "3.37.2"

runs:
  using: "composite"
  steps:
    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        version: ${{ inputs.task-version }}

    - name: Install Rust
      shell: bash
      run: rustup update stable

    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov
