name: Check PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  check-pr:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup_environment

      - name: Install Dependencies
        run: |
          task init

      - name: Lint PR
        run: |
          task lint

      - name: Test PR
        run: |
          task test
