name: Release PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  release-pr:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup_environment

      - name: Configure Docker Builder
        run: task build:configure-builder

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Image Tag
        id: get-image-tag
        run: echo "image-tag=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-beta:${{ github.event.number }}-${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT

      - name: Build binaries and images
        run: task build:all
        env:
          IMAGE_TAG: ${{ steps.get-image-tag.outputs.image-tag }}

      - name: Release binaries
        id: release-binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: build/bin

      - name: Comment on PR
        uses: ovsds/create-or-update-unique-comment-action@v1
        with:
          issue-number: ${{ github.event.number }}
          body: |
            Build Artifacts:
              - Binaries: [download](${{ steps.release-binaries.outputs.artifact-url }})
              - Image Tag: `${{ steps.get-image-tag.outputs.image-tag }}`
          unique-body-includes: |
            Build Artifacts:
